export const cities = [
  "kathmandu",
  "dharan",
  "mahendranagar",
  "pokhara",
  "bharatpur",
  "hetauda",
  "patan",
  "janakpur",
  "madhyapur thimi",
  "biratnagar",
  "dhangadhi",
  "triyuga",
  "birgunj",
  "butwal",
];

export const DUMMPY_PRODUCTS = [
  {
    title: "Af-1 White Interlocked Sneakers For Women By Jutta Collection",
    date: "Feb 13th, 2024 at 11:15",
    label: "Automobile",
    address: "Bhaktapur",
    price: 892,
    rating: 4.6,
    image: "/images/bike.png",
  },
  {
    title: "Af-1 White Interlocked Sneakers For Women By Jutta Collection",
    date: "Feb 13th, 2024 at 11:15",
    label: "Automobile",
    address: "Bhaktapur",
    price: 892,
    rating: 4.6,
    image: "/images/bike.png",
  },
  {
    title: "Af-1 White Interlocked Sneakers For Women By Jutta Collection",
    date: "Feb 13th, 2024 at 11:15",
    label: "Automobile",
    address: "Bhaktapur",
    price: 892,
    rating: 4.6,
    image: "/images/bike.png",
  },
  {
    title: "Af-1 White Interlocked Sneakers For Women By Jutta Collection",
    date: "Feb 13th, 2024 at 11:15",
    label: "Automobile",
    address: "Bhaktapur",
    price: 892,
    rating: 4.6,
    image: "/images/bike.png",
  },
  {
    title: "Af-1 White Interlocked Sneakers For Women By Jutta Collection",
    date: "Feb 13th, 2024 at 11:15",
    label: "Automobile",
    address: "Bhaktapur",
    price: 892,
    rating: 4.6,
    image: "/images/bike.png",
  },
  {
    title: "Af-1 White Interlocked Sneakers For Women By Jutta Collection",
    date: "Feb 13th, 2024 at 11:15",
    label: "Automobile",
    address: "Bhaktapur",
    price: 892,
    rating: 4.6,
    image: "/images/bike.png",
  },
  {
    title: "Af-1 White Interlocked Sneakers For Women By Jutta Collection",
    date: "Feb 13th, 2024 at 11:15",
    label: "Automobile",
    address: "Bhaktapur",
    price: 892,
    rating: 4.6,
    image: "/images/bike.png",
  },
  {
    title: "Af-1 White Interlocked Sneakers For Women By Jutta Collection",
    date: "Feb 13th, 2024 at 11:15",
    label: "Automobile",
    address: "Bhaktapur",
    price: 892,
    rating: 4.6,
    image: "/images/bike.png",
  },
];
